eureka:
  client:
    service-url:
      defaultZone: http://ulug618:ulug618@127.0.0.1:9090/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  level:
    root: info
server:
  port: 9092
spring:
  cloud:
    client:
      ip-address: 127.0.0.1
    stream:
      bindings:
        task-in-0:
          destination: ulug-task
          group: cms
      function:
        definition: task
      kafka:
        binder:
          brokers: localhost:9099
          zkNodes: localhost:2182
  datasource:
    password: ulug
    url: jdbc:mysql://127.0.0.1:3306/ulug_cms
    username: ulug
  devtools:
    add-properties: false
  jpa:
    hibernate:
      show-sql: true
  redis:
    host: 127.0.0.1
#    password: tswcbyyqjsjhfl
    port: 6379
project:
  media:
    disk:
      path: D:/Container
      #网盘默认大小(M)
      default-size: 2000