project:
  auth:
    active:
      time: 1800
    aes:
      key: 1616161616161616
    default:
      password: 000000
    developer:
      code: De
    error:
      times: 5
  scanning-ability:
    'on': false
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript
    min-response-size: 2048
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: ulug-core
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 60000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 5
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: pro
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
