eureka:
  client:
    service-url:
      defaultZone: http://ulug618:ulug618@127.0.0.1:9090/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
logging:
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  level:
    root: info
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过2KB自动归档，次日启动服务时也会自动归档
      file-name-pattern: ./logs/%d{yyyyMMdd}/${spring.application.name}.out.log.%d{yyyy-MM-dd}.%i.gz
      # 最大日志文件大小(默认为10MB，这里为了测试归档，暂时设置为2KB)
      max-file-size: 10MB
      # 要保留的日志备份的总大小(默认为0B)
      total-size-cap: 200MB
      # 保存存档日志文件的最大天数(默认为7天)
      max-history: 3
server:
  port: 9091
spring:
  cloud:
    client:
      ip-address: 127.0.0.1
    stream:
      kafka:
        binder:
          brokers: localhost:9099
          zkNodes: localhost:2182
  datasource:
    password: tswcbyyqjsjhfl@db
    url: jdbc:mysql://127.0.0.1:3306/ulug_core
    username: ulug_cool
  devtools:
    add-properties: false
  redis:
    host: 127.0.0.1
    password: tswcbyyqjsjhfl
    port: 6379
project:
  node:
    address: 127.0.0.1
    dist: dist
    path: /u01/ug-dist/node-mgr
    zip: node-server.zip