eureka:
  instance:
    prefer-ip-address: true
project:
  auth:
    active:
      time: 1440
    aes:
      key: CHYNULUG20210618
    default:
      password: 210618
    developer:
      code: De
    error:
      times: 5
  scanning-ability:
    'on': true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript
    min-response-size: 2048
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: ulug-core
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 60000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 5
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: false
            misfireThreshold: 60000
            tablePrefix: QRTZ_
            useProperties: false
          scheduler:
            instanceId: AUTO
            instanceName: JobScheduler
            rmi:
              export: false
              proxy: false
            wrapJobExecutionInUserTransaction: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
  redis:
    database: 4
    pool:
      max-active: 300
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 5000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
