server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript
    min-response-size: 2048
spring:
  application.name: ulug-core
  profiles.active: security,pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 60000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 5
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    properties.hibernate.event.merge.entity_copy_observer: allow
  main.allow-bean-definition-overriding: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false